requirements:
  "3.2": [
    "bzip2/1.0.8",
    "zlib/[>=1.2.11 <2]",
    "zstd/[>=1.5.5 <=1.5.6]"
  ]
  "3.1": [
    "bzip2/1.0.8",
    "zlib/[>=1.2.11 <2]",
    "zstd/1.5.5"
  ]
  "3.0": [
    "bzip2/1.0.8",
    "zlib/[>=1.2.11 <2]",
    "zstd/1.5.5"
  ]
  "0.0": [
    "bzip2/1.0.8",
    "zlib/[>=1.2.11 <2]",
    "zstd/1.5.5"
  ]
